<script setup lang="ts">
import { onMounted, ref, watch } from 'vue'
import { Plus, Search } from '@lucide/vue'
import { useCommunicationStore } from '../../stores/useCommunicationStore'
import { useTermStore } from '../../stores/useTermStore'
const store = useCommunicationStore(); const termStore = useTermStore(); const targetType = ref(''); const keyword = ref(''); const date = ref('')
const filters = [['','全部'],['parent','👨‍👩‍👦 家长'],['teacher','👩‍🏫 班主任'],['leader','🏛️ 领导']] as const
const targetLabels = { parent: '家长', teacher: '班主任', leader: '学校领导', other: '其他' }; const modeLabels = { phone: '电话', wechat: '微信', in_person: '面对面', meeting: '专题会议' }
async function load() { await store.fetchLogs({ targetType: targetType.value as any, keyword: keyword.value, date: date.value }) }
watch([targetType, keyword, date, () => termStore.currentTermId], () => void load())
onMounted(load)
</script>
<template><div class="flex h-full min-h-0 flex-col"><header class="shrink-0 space-y-3 border-b border-slate-100 p-4"><div class="flex items-center justify-between"><span class="text-sm font-semibold text-slate-800">协同沟通</span><button type="button" class="inline-flex items-center gap-1 rounded-lg bg-emerald-600 px-2.5 py-1.5 text-xs font-semibold text-white" @click="store.openForm()"><Plus :size="15" />新增记录</button></div><div class="flex flex-wrap gap-1"><button v-for="item in filters" :key="item[0]" type="button" class="rounded-full px-2 py-1 text-[11px]" :class="targetType === item[0] ? 'bg-emerald-600 text-white' : 'bg-slate-100 text-slate-600'" @click="targetType = item[0]">{{ item[1] }}</button></div><label class="flex items-center gap-2 rounded-lg border border-slate-200 px-2 py-1.5 text-xs text-slate-400"><Search :size="14" /><input v-model="keyword" class="min-w-0 bg-transparent outline-none" placeholder="搜学生姓名" /></label><input v-model="date" type="date" class="w-full rounded-lg border border-slate-200 px-2 py-1.5 text-xs" /></header><div class="min-h-0 flex-1 overflow-y-auto p-3"><p v-if="!store.logs.length" class="p-6 text-center text-sm text-slate-400">暂无沟通记录</p><button v-for="log in store.logs" v-else :key="log.id" type="button" class="mb-2 w-full rounded-xl border border-slate-200 bg-white p-3 text-left hover:border-emerald-300 hover:bg-emerald-50/30" :class="store.selectedLogId === log.id ? 'border-emerald-400 bg-emerald-50' : ''" @click="store.openDetail(log.id)"><div class="flex items-start justify-between gap-2"><p class="font-semibold text-slate-800">{{ log.studentName }}</p><time class="text-[11px] text-slate-400">{{ log.dateTime }}</time></div><p class="mt-1 text-xs text-emerald-700">{{ targetLabels[log.targetType] }}：{{ log.targetName }} · {{ modeLabels[log.communicationMode] }}</p><p class="mt-2 line-clamp-2 text-xs leading-5 text-slate-500">{{ log.summary }}</p><span v-if="log.attachments.length" class="mt-2 inline-flex rounded bg-slate-100 px-1.5 py-0.5 text-[10px] text-slate-500">📎 {{ log.attachments.length }} 个附件</span></button></div></div></template>
