<script setup lang="ts">
import { ref } from 'vue'
import * as XLSX from 'xlsx'
import { studentService } from '../../services/studentService'
import { useTermStore } from '../../stores/term'
import type { Student } from '../../types/schema'
const emit = defineEmits<{ close: []; imported: [] }>(); const termStore=useTermStore(); const rows=ref<Array<{student: Omit<Student,'id'|'createdAt'|'updatedAt'>; error?:string}>>([])
function template(){const sheet=XLSX.utils.json_to_sheet([{学号:'20250001',姓名:'示例学生',性别:'女',班级:'1班',紧急联系人:'家长',联系电话:'13800000000',标签:'学业关注'}]);const book=XLSX.utils.book_new();XLSX.utils.book_append_sheet(book,sheet,'新初一');XLSX.writeFile(book,'新初一学生导入模板.xlsx')}
async function read(file:File){const data=await file.arrayBuffer();const workbook=XLSX.read(data);const sheet=XLSX.utils.sheet_to_json<Record<string,string>>(workbook.Sheets[workbook.SheetNames[0]],{defval:''});const existing=await studentService.list();const seen=new Set(existing.map(s=>s.studentNo));rows.value=sheet.map(r=>{const student={studentNo:String(r.学号).trim(),name:String(r.姓名).trim(),gender:(r.性别==='男'?'male':r.性别==='女'?'female':'other') as Student['gender'],enrollmentYear:termStore.currentTerm.startYear,status:'active' as const,grade:'初一',className:String(r.班级).trim(),emergencyContact:{name:String(r.紧急联系人).trim()||'未填写',relation:'监护人',phone:String(r.联系电话).trim()||'未填写'},riskLevel:'normal' as const,tags:String(r.标签).split(/[，,]/).map(x=>x.trim()).filter(Boolean)};const error=!student.studentNo||!student.name||!student.className?'缺少必填项':seen.has(student.studentNo)?'学号重复':'';seen.add(student.studentNo);return {student,error:error||undefined}})}
async function confirm(){const valid=rows.value.filter(x=>!x.error).map(x=>x.student);if(valid.length) await studentService.importStudents(valid);emit('imported');emit('close')}
</script><template><div class="fixed inset-0 z-50 flex items-center justify-center bg-stone-950/30 p-4"><section class="w-full max-w-3xl rounded-2xl bg-white p-6 shadow-xl"><div class="flex items-center justify-between"><h2 class="font-semibold">批量导入新初一学生</h2><button class="text-sm text-stone-500" @click="emit('close')">关闭</button></div><p class="mt-2 text-sm text-stone-500">导入数据只在本机解析；入学年份自动采用 {{ termStore.currentTerm.startYear }}。</p><div class="mt-4 flex gap-3"><button class="rounded-lg border px-3 py-2 text-sm" @click="template">下载模板</button><label class="rounded-lg bg-teal-700 px-3 py-2 text-sm text-white">选择 Excel / CSV<input class="hidden" type="file" accept=".xlsx,.csv" @change="read(($event.target as HTMLInputElement).files?.[0]!)" /></label></div><div v-if="rows.length" class="mt-4 max-h-64 overflow-auto border rounded-lg"><table class="w-full text-sm"><tr class="bg-stone-50 text-left"><th class="p-2">学号</th><th>姓名</th><th>班级</th><th>校验</th></tr><tr v-for="row in rows" :class="row.error?'bg-rose-50':''"><td class="p-2">{{row.student.studentNo}}</td><td>{{row.student.name}}</td><td>{{row.student.className}}</td><td>{{row.error||'通过'}}</td></tr></table></div><button :disabled="!rows.length" class="mt-4 rounded-lg bg-teal-700 px-4 py-2 text-sm text-white disabled:opacity-50" @click="confirm">确认导入</button></section></div></template>
