<script setup lang="ts">
import { ref } from 'vue'
import { X } from '@lucide/vue'
import type { WorkTrail } from '../../types/schema'
defineProps<{ trail: WorkTrail }>()
const emit = defineEmits<{ close: [] }>()
const preview = ref<string | null>(null)
const categoryLabels = { parent: '家长沟通', teacher: '班主任协同', leader: '领导指令', handover: '任务交接', subbing: '代课与杂务', disclaimer: '危机免责存证' }
</script>
<template><Teleport to="body"><div class="fixed inset-0 z-50 bg-slate-950/30" @click.self="emit('close')"><section class="ml-auto flex h-full w-full max-w-xl flex-col overflow-y-auto bg-white p-6 shadow-2xl"><header class="flex items-start justify-between gap-4"><div><p class="text-xs tabular-nums text-emerald-700">{{ trail.dateTime }}</p><h2 class="mt-1 text-lg font-semibold text-slate-800">{{ trail.title }}</h2><p class="mt-1 text-sm text-slate-500">{{ categoryLabels[trail.category] }} · {{ trail.stakeholderName }}<span v-if="trail.studentName"> · {{ trail.studentName }}</span></p></div><button type="button" class="rounded p-1 text-slate-400 hover:bg-slate-100" @click="emit('close')"><X :size="18" /></button></header><section class="mt-6"><h3 class="text-sm font-semibold text-slate-700">过程记录</h3><p class="mt-2 whitespace-pre-wrap text-sm leading-7 text-slate-600">{{ trail.content }}</p></section><section v-if="trail.attachments.length" class="mt-6"><h3 class="text-sm font-semibold text-slate-700">证明文件</h3><div class="mt-3 space-y-3"><article v-for="file in trail.attachments" :key="file.id" class="rounded-xl border border-slate-200 p-3"><img v-if="file.type === 'image'" :src="file.url" class="max-h-44 cursor-zoom-in rounded object-cover" @click="preview = file.url" /><audio v-else-if="file.type === 'audio'" class="w-full" controls :src="file.url" /><video v-else-if="file.type === 'video'" class="max-h-52 w-full rounded" controls :src="file.url" /><a v-else :href="file.url" :download="file.name" class="text-sm text-emerald-700">{{ file.name }}</a><p class="mt-2 text-xs text-slate-400">{{ file.name }} · {{ file.size }}</p></article></div></section></section><div v-if="preview" class="fixed inset-0 z-[60] flex items-center justify-center bg-slate-950/80 p-6" @click="preview = null"><img :src="preview" class="max-h-full max-w-full rounded" /></div></div></Teleport></template>
