<script setup lang="ts">
import { onMounted, ref, watch } from 'vue'
import { Plus, Search } from '@lucide/vue'
import { useWorkTrailStore } from '../../stores/useWorkTrailStore'
import type { WorkTrail } from '../../types/schema'

const store = useWorkTrailStore()
const selectedCategory = ref<'all' | 'leader' | 'parent' | 'subbing' | 'disclaimer'>('all')
const keyword = ref('')
const date = ref('')
const categoryMap: Record<typeof selectedCategory.value, WorkTrail['category'][]> = { all: [], leader: ['leader', 'handover'], parent: ['parent', 'teacher'], subbing: ['subbing'], disclaimer: ['disclaimer'] }
const categoryLabels: Record<WorkTrail['category'], string> = { parent: '家长沟通', teacher: '班主任协同', leader: '领导指令', handover: '任务交接', subbing: '代课与杂务', disclaimer: '危机免责' }
function attachmentSummary(trail: WorkTrail) { const count = (type: string) => trail.attachments.filter((item) => item.type === type).length; return [['📷', count('image')], ['🎙️', count('audio')], ['📄', count('file')]].filter(([, total]) => total).map(([icon, total]) => `${icon} ${total}`).join(' · ') }
async function load() { await store.fetchTrails({ category: categoryMap[selectedCategory.value], keyword: keyword.value, date: date.value }) }
watch([selectedCategory, keyword, date], () => void load())
onMounted(load)
</script>
<template><div class="flex h-full min-h-0 flex-col"><header class="shrink-0 space-y-2.5 border-b border-slate-100 p-3"><div class="flex items-center justify-between"><span class="text-sm font-semibold text-slate-800">工作留痕</span><button type="button" class="inline-flex items-center gap-1 rounded-lg bg-emerald-600 px-2.5 py-1.5 text-xs font-semibold text-white" @click="store.openForm()"><Plus :size="15" />新增留痕</button></div><select v-model="selectedCategory" class="h-9 w-full rounded-lg border border-slate-200 bg-slate-50 px-3 text-sm text-slate-700 outline-none transition-all focus:border-emerald-500 focus:bg-white"><option value="all">📂 全部分类</option><option value="leader">🏛️ 领导指令 / 任务交接</option><option value="parent">👨‍👩‍👦 家长沟通 / 学生谈话</option><option value="subbing">📢 杂务代课 / 兼职留痕</option><option value="disclaimer">⚖️ 危机免责 / 告知存证</option></select><label class="flex h-9 items-center gap-2 rounded-lg border border-slate-200 bg-slate-50 px-2.5 text-sm text-slate-400 focus-within:border-emerald-500 focus-within:bg-white"><Search :size="14" /><input v-model="keyword" class="min-w-0 flex-1 bg-transparent outline-none" placeholder="搜姓名/对接人/主题" /></label><input v-model="date" type="date" class="h-9 w-full rounded-lg border border-slate-200 bg-slate-50 px-2.5 text-sm text-slate-600 outline-none focus:border-emerald-500 focus:bg-white" /></header><div class="min-h-0 flex-1 overflow-y-auto p-3"><div v-if="!store.trails.length" class="flex flex-col items-center px-4 py-12 text-center"><span class="flex size-12 items-center justify-center rounded-2xl bg-emerald-50 text-xl">🛡️</span><p class="mt-3 text-sm font-medium text-slate-600">暂无工作留痕</p><p class="mt-1 text-xs leading-5 text-slate-400">点击「+ 新增留痕」留下工作轨迹</p></div><button v-for="trail in store.trails" v-else :key="trail.id" type="button" class="mb-2 w-full rounded-xl border border-slate-200 bg-white p-3 text-left hover:border-emerald-300 hover:bg-emerald-50/30" :class="store.selectedTrailId === trail.id ? 'border-emerald-400 bg-emerald-50' : ''" @click="store.openDetail(trail.id)"><div class="flex items-start justify-between gap-2"><time class="text-[11px] tabular-nums text-slate-500">{{ trail.dateTime }}</time><span class="rounded-full bg-slate-100 px-1.5 py-0.5 text-[10px] font-medium text-slate-600">{{ categoryLabels[trail.category] }}</span></div><p class="mt-1.5 truncate text-sm font-semibold text-slate-800">{{ trail.title }}</p><p class="mt-1 text-xs text-emerald-700">{{ trail.stakeholderName }}<span v-if="trail.studentName"> · {{ trail.studentName }}</span></p><p class="mt-2 line-clamp-2 text-xs leading-5 text-slate-500">{{ trail.content }}</p><span v-if="trail.attachments.length" class="mt-2 inline-flex rounded bg-slate-100 px-1.5 py-0.5 text-[10px] text-slate-500">{{ attachmentSummary(trail) || `📎 ${trail.attachments.length}` }}</span></button></div></div></template>
