<script setup lang="ts">
import { computed, ref } from 'vue'
import { Copy, Plus, Search, Trash2 } from '@lucide/vue'
import { useTeachingStore } from '../../stores/useTeachingStore'
import TeachingMaterialDrawer from './TeachingMaterialDrawer.vue'
import type { TeachingMaterial } from '../../types/schema'

const teachingStore = useTeachingStore(); const keyword = ref(''); const type = ref(''); const drawerOpen = ref(false); const editingId = ref<string | null>(null); const message = ref('')
const labels: Record<string, string> = { video: '🎬 心理短片与视频', activity: '💡 破冰与互动游戏', case: '🖼️ 案例与图解素材', survey: '📊 课堂小测量与问卷', reference: '📂 参考 PPT 与讲义', document: '📂 参考 PPT 与讲义', lesson_plan: '📂 历史素材', style: '🖼️ 案例与图解素材' }
const materials = computed(() => teachingStore.teachingMaterials.filter((item) => (!type.value || item.type === type.value) && (!keyword.value.trim() || [item.title, item.description, item.resourceNote, ...(item.tags ?? [])].join(' ').includes(keyword.value.trim()))))
async function reference(material: TeachingMaterial) { teachingStore.prepareMaterialReference(material); const text = teachingStore.pendingPlanReference; try { await navigator.clipboard?.writeText(text) } catch { /* 本地浏览器可能禁止剪贴板，但引用仍会传给下一份新教案。 */ } message.value = '素材已复制，并会自动带入下一份新建教案的资源备注。' }
async function remove(material: TeachingMaterial) { if (!window.confirm(`确定删除素材“${material.title}”吗？`)) return; try { await teachingStore.deleteTeachingMaterial(material.id) } catch (error) { message.value = error instanceof Error ? error.message : '删除失败。' } }
</script>

<template><section><header class="flex flex-wrap items-end justify-between gap-4"><div><h2 class="text-lg font-semibold text-stone-800">备课素材库</h2></div><button class="inline-flex items-center gap-1.5 rounded-lg bg-teal-700 px-4 py-2.5 text-sm font-semibold text-white hover:bg-teal-800" @click="editingId = null; drawerOpen = true"><Plus :size="16" />新增素材</button></header><p v-if="message" class="mt-4 rounded-lg bg-teal-50 px-3 py-2 text-sm text-teal-800">{{ message }}</p><div class="mt-5 flex flex-wrap gap-2"><label class="flex min-w-60 flex-1 items-center gap-2 rounded-lg border border-stone-200 bg-white px-3 py-2 text-sm text-stone-400"><Search :size="15" /><input v-model="keyword" class="w-full bg-transparent outline-none" placeholder="搜索素材、标签或链接" /></label><select v-model="type" class="rounded-lg border border-stone-200 bg-white px-3 py-2 text-sm"><option value="">全部类别</option><option value="video">🎬 心理短片与视频</option><option value="activity">💡 破冰与互动游戏</option><option value="case">🖼️ 案例与图解素材</option><option value="survey">📊 课堂小测量与问卷</option><option value="reference">📂 参考 PPT 与讲义</option></select></div><div class="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-3"><article v-for="material in materials" :key="material.id" class="rounded-2xl border border-stone-200 bg-white p-5 shadow-sm"><div class="flex items-start justify-between gap-3"><p class="text-xs font-medium text-teal-700">{{ labels[material.type] || '📂 备课素材' }}</p><div class="flex items-center gap-2"><button class="text-xs text-stone-400 hover:text-teal-700" @click="editingId = material.id; drawerOpen = true">编辑</button><button type="button" class="rounded p-1 text-rose-500 hover:bg-rose-50" :aria-label="`删除 ${material.title}`" @click="remove(material)"><Trash2 :size="14" /></button></div></div><h3 class="mt-2 text-base font-semibold text-stone-800">{{ material.title }}</h3><p class="mt-2 line-clamp-3 text-sm leading-6 text-stone-600">{{ material.description || material.resourceNote || '未填写说明。' }}</p><div class="mt-3 flex flex-wrap gap-1"><span v-for="tag in material.tags" :key="tag" class="rounded-full bg-stone-100 px-2 py-0.5 text-[10px] text-stone-600">{{ tag }}</span></div><a v-if="material.attachment" :href="material.attachment.dataUrl" :download="material.attachment.name" class="mt-3 inline-flex text-xs font-medium text-stone-500 hover:text-teal-700">下载附件：{{ material.attachment.name }}</a><button class="mt-4 inline-flex items-center gap-1.5 rounded-lg border border-teal-200 px-3 py-2 text-xs font-semibold text-teal-800 hover:bg-teal-50" @click="reference(material)"><Copy :size="14" />引用到新教案</button></article><p v-if="!materials.length" class="col-span-full rounded-xl border border-dashed border-stone-300 p-10 text-center text-sm text-stone-400">还没有符合条件的备课素材。</p></div><TeachingMaterialDrawer v-if="drawerOpen" :editing-id="editingId" @close="drawerOpen = false" @saved="teachingStore.fetchTeachingData()" /></section></template>
