<script setup lang="ts">
import { computed, onMounted, ref, watch } from 'vue'
import { BookOpenCheck, CalendarDays, LayoutGrid } from '@lucide/vue'
import { useSchoolConfigStore } from '../../stores/useSchoolConfigStore'
import { useTeachingStore } from '../../stores/useTeachingStore'
import { useTermStore } from '../../stores/useTermStore'
import type { CourseProgress, LessonPlan, ScheduleFrequency, WeeklySchedule } from '../../types/schema'
import CourseProgressMatrix from '../../components/lesson/CourseProgressMatrix.vue'
import WeeklyScheduleGrid from '../../components/lesson/WeeklyScheduleGrid.vue'
import MaterialLibrary from '../../components/lesson/MaterialLibrary.vue'
import SchedulePlacementModal from '../../components/lesson/SchedulePlacementModal.vue'
import CreateProgressUnitModal from '../../components/lesson/CreateProgressUnitModal.vue'
import LessonLogDrawer from '../../components/lesson/LessonLogDrawer.vue'
type Tab = 'progress' | 'schedule' | 'materials'
type Detail = { plan: LessonPlan | null; grade: string; className: string; schedule?: WeeklySchedule | null; progress?: CourseProgress | null }
type Placement = { plan?: LessonPlan | null; existingSchedule?: WeeklySchedule | null; dayOfWeek: number; period: number; frequency: ScheduleFrequency }
const teachingStore = useTeachingStore(); const schoolConfig = useSchoolConfigStore(); const termStore = useTermStore()
const activeTab = ref<Tab>('progress'); const scheduleView = ref<'all' | 'single' | 'double'>('all'); const placement = ref<Placement | null>(null); const progressUnitOpen = ref(false); const progressUnitPlanId = ref<string | undefined>(); const detail = ref<Detail | null>(null)
const tabs = [{ id: 'progress' as const, label: '课程进度大盘', icon: LayoutGrid }, { id: 'schedule' as const, label: '完整心理周课表', icon: CalendarDays }, { id: 'materials' as const, label: '备课素材库', icon: BookOpenCheck }]
// 教学班级只由“学校与教学配置”定义，绝不依赖学生档案是否已录入。
const classes = computed(() => schoolConfig.enabledGrades.flatMap((grade) => schoolConfig.classesForGrade(grade).map((className) => ({ grade, className }))))
function openMatrix(plan: LessonPlan, schedule: WeeklySchedule | null) { detail.value = { plan, grade: schedule?.grade ?? '', className: schedule?.className ?? '', schedule, progress: schedule?.lessonPlanId ? teachingStore.courseProgress.find((item) => item.lessonPlanId === schedule.lessonPlanId && item.grade === schedule.grade && item.className === schedule.className) ?? null : null } }
function requestProgressUnit(planId?: string) { progressUnitPlanId.value = planId; progressUnitOpen.value = true }
function openSchedule(schedule: WeeklySchedule) { detail.value = { plan: schedule.lessonPlanId ? teachingStore.planById.get(schedule.lessonPlanId) ?? null : null, grade: schedule.grade, className: schedule.className, schedule, progress: schedule.lessonPlanId ? teachingStore.courseProgress.find((item) => item.lessonPlanId === schedule.lessonPlanId && item.grade === schedule.grade && item.className === schedule.className) ?? null : null } }
function configureSchedule(schedule: WeeklySchedule | null, dayOfWeek: number, period: number, frequency: ScheduleFrequency, planId?: string) { placement.value = { plan: planId ? teachingStore.planById.get(planId) ?? null : schedule?.lessonPlanId ? teachingStore.planById.get(schedule.lessonPlanId) ?? null : null, existingSchedule: schedule, dayOfWeek, period, frequency } }
async function load() { await Promise.all([schoolConfig.load(), teachingStore.fetchTeachingData()]) }
watch(() => termStore.currentTermId, () => void load())
watch(() => teachingStore.progressUnitRequestId, (planId) => { if (planId) { teachingStore.consumeProgressUnitRequest(); requestProgressUnit(planId) } })
onMounted(async () => { await load(); const planId = teachingStore.consumeProgressUnitRequest(); if (planId) requestProgressUnit(planId) })
</script>
<template><section class="flex h-full min-h-0 flex-col overflow-hidden"><header class="shrink-0 border-b border-slate-200 bg-white px-6 pt-3"><div class="flex h-10 items-center justify-between border-b border-slate-200"><nav class="flex shrink-0 items-center space-x-6" aria-label="教学工作台页签"><button v-for="tab in tabs" :key="tab.id" type="button" class="border-b-2 px-1 py-2 text-sm whitespace-nowrap" :class="activeTab === tab.id ? 'border-emerald-600 font-bold text-emerald-600' : 'border-transparent text-slate-500 hover:text-slate-800'" @click="activeTab = tab.id"><component :is="tab.icon" :size="16" class="mr-1 inline" />{{ tab.label }}</button></nav><div class="ml-4 flex min-w-0 items-center justify-end space-x-2"><div v-if="activeTab === 'schedule'" class="flex shrink-0 rounded-lg border border-slate-200 bg-slate-50 p-0.5"><button type="button" class="rounded-md px-2.5 py-1.5 text-xs font-medium" :class="scheduleView === 'all' ? 'bg-emerald-600 text-white shadow-sm' : 'text-slate-600 hover:bg-slate-200'" @click="scheduleView = 'all'">看课表</button><button type="button" class="rounded-md px-2.5 py-1.5 text-xs font-medium" :class="scheduleView === 'single' ? 'bg-emerald-600 text-white shadow-sm' : 'text-slate-600 hover:bg-slate-200'" @click="scheduleView = 'single'">仅单周</button><button type="button" class="rounded-md px-2.5 py-1.5 text-xs font-medium" :class="scheduleView === 'double' ? 'bg-emerald-600 text-white shadow-sm' : 'text-slate-600 hover:bg-slate-200'" @click="scheduleView = 'double'">仅双周</button></div></div></div></header><div class="min-h-0 flex-1 overflow-y-auto bg-slate-50/60 p-4"><div class="mx-auto max-w-7xl"><CourseProgressMatrix v-if="activeTab === 'progress'" :classes="classes" @open="openMatrix" @request-unit="requestProgressUnit" /><WeeklyScheduleGrid v-else-if="activeTab === 'schedule'" v-model:view="scheduleView" @configure="configureSchedule" @open="openSchedule" /><MaterialLibrary v-else /></div></div><CreateProgressUnitModal v-if="progressUnitOpen" :initial-plan-id="progressUnitPlanId" :grades="schoolConfig.enabledGrades" @close="progressUnitOpen = false; progressUnitPlanId = undefined" @saved="progressUnitOpen = false; progressUnitPlanId = undefined; load()" /><SchedulePlacementModal v-if="placement" :plan="placement.plan" :existing-schedule="placement.existingSchedule" :day-of-week="placement.dayOfWeek" :period="placement.period" :frequency="placement.frequency" :classes="classes" @close="placement = null" @saved="placement = null; load()" /><LessonLogDrawer v-if="detail" v-bind="detail" @close="detail = null" @changed="load" /></section></template>
