<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { Pencil, ShieldPlus, Trash2 } from '@lucide/vue'
import WorkTrailFormModal from '../../components/work-trail/WorkTrailFormModal.vue'
import { useWorkTrailStore } from '../../stores/useWorkTrailStore'

const store = useWorkTrailStore()
const selected = computed(() => store.selectedTrail)
const preview = ref<string | null>(null)
const categoryLabels = { parent: '家长沟通', teacher: '班主任协同', leader: '领导指令', handover: '任务交接', subbing: '代课与杂务', disclaimer: '危机免责存证' }
async function remove() { if (!selected.value || !window.confirm('确定删除该工作留痕吗？')) return; await store.deleteTrail(selected.value.id) }
onMounted(() => void store.fetchTrails())
</script>
<template><section class="flex h-full min-h-0 flex-col overflow-hidden"><div v-if="!selected" class="flex flex-1 flex-col items-center justify-center p-8 text-center"><span class="flex size-14 items-center justify-center rounded-2xl bg-emerald-50 text-emerald-700"><ShieldPlus :size="25" /></span><p class="mt-4 text-sm font-medium text-slate-600">👈 请在左侧选择一条留痕记录查看详细存证</p></div><div v-else class="flex flex-1 flex-col overflow-y-auto p-6"><div class="flex items-start justify-between border-b border-slate-200 pb-5"><div><p class="text-sm text-emerald-700">{{ selected.dateTime }}</p><h1 class="mt-1 text-xl font-semibold text-slate-800">{{ selected.title }}</h1><p class="mt-1 text-sm text-slate-500">{{ categoryLabels[selected.category] }} · {{ selected.stakeholderName }}<span v-if="selected.studentName"> · {{ selected.studentName }}</span></p></div><div class="flex gap-2"><button type="button" class="rounded-lg border border-slate-200 p-2 text-slate-500" @click="store.openForm(selected.id)"><Pencil :size="16" /></button><button type="button" class="rounded-lg border border-rose-200 p-2 text-rose-600" @click="remove"><Trash2 :size="16" /></button></div></div><p class="mt-5 whitespace-pre-wrap text-sm leading-7 text-slate-600">{{ selected.content }}</p><section v-if="selected.attachments?.length" class="mt-6 border-t border-slate-100 pt-5"><h2 class="text-sm font-semibold text-slate-800">附件存证</h2><div class="mt-3 grid gap-3 sm:grid-cols-2"><article v-for="file in selected.attachments" :key="file.id" class="rounded-xl border border-slate-200 bg-slate-50 p-3"><button v-if="file.type === 'image'" type="button" class="block w-full text-left" @click="preview = file.url"><img :src="file.url" :alt="file.name" class="max-h-48 w-full rounded-lg object-contain" /></button><audio v-else-if="file.type === 'audio'" :src="file.url" controls class="w-full" /><video v-else-if="file.type === 'video'" :src="file.url" controls class="max-h-48 w-full rounded-lg" /><a v-else :href="file.url" :download="file.name" class="text-sm text-emerald-700 underline">{{ file.name }}</a><p class="mt-2 truncate text-xs text-slate-500">{{ file.name }} · {{ file.size }}</p></article></div></section></div><Transition name="toast"><div v-if="store.toast" class="fixed right-6 top-20 z-[70] rounded-xl border px-4 py-3 text-sm font-medium shadow-lg" :class="store.toast.type === 'success' ? 'border-emerald-200 bg-emerald-50 text-emerald-800' : store.toast.type === 'warning' ? 'border-amber-200 bg-amber-50 text-amber-800' : 'border-rose-200 bg-rose-50 text-rose-800'">{{ store.toast.message }}</div></Transition><WorkTrailFormModal v-if="store.isFormOpen" :editing-id="store.editingTrailId" @saved="store.fetchTrails()" /><div v-if="preview" class="fixed inset-0 z-[80] flex items-center justify-center bg-slate-950/80 p-6" @click="preview = null"><img :src="preview" class="max-h-full max-w-full rounded-xl object-contain" /></div></section></template>
<style scoped>.toast-enter-active,.toast-leave-active{transition:all .2s ease}.toast-enter-from,.toast-leave-to{opacity:0;transform:translateY(-8px)}</style>
