<script setup lang="ts">
import { computed, onMounted, reactive, ref, watch } from 'vue'
import { AlertTriangle, ClipboardList, FileBarChart2, History, PencilLine, Save, Trash2, UserRound } from '@lucide/vue'
import StudentTimeline from '../../components/student/StudentTimeline.vue'
import { studentService, type StudentCensusResult } from '../../services/studentService'
import { useWorkbenchStore } from '../../stores/workbench'
import type { ConsultationRecord, RiskLevel, Student } from '../../types/schema'

const workbench = useWorkbenchStore()
const student = ref<Student | undefined>()
const consultations = ref<ConsultationRecord[]>([])
const censusResults = ref<StudentCensusResult[]>([])
const loading = ref(false)
const activeTab = ref<'timeline' | 'consultations' | 'census' | 'edit'>('timeline')
const editForm = reactive({ name: '', studentNo: '', gender: 'female' as Student['gender'], grade: '', className: '', dormNumber: '', contactName: '', relation: '', phone: '', tags: '' })
const riskClass: Record<RiskLevel, string> = { normal: 'bg-emerald-50 text-emerald-700', attention: 'bg-amber-50 text-amber-700', warning: 'bg-orange-50 text-orange-700', crisis: 'bg-rose-50 text-rose-700' }
const tabs = [{ id: 'timeline', label: '服务履历', icon: History }, { id: 'consultations', label: '咨询历史', icon: ClipboardList }, { id: 'census', label: '普查数据', icon: FileBarChart2 }, { id: 'edit', label: '档案编辑', icon: PencilLine }] as const
const hasStudent = computed(() => Boolean(student.value))

function fillEditForm(record: Student) { Object.assign(editForm, { name: record.name, studentNo: record.studentNo, gender: record.gender, grade: record.grade, className: record.className, dormNumber: record.dormNumber ?? '', contactName: record.emergencyContact.name, relation: record.emergencyContact.relation, phone: record.emergencyContact.phone, tags: record.tags.join('，') }) }
async function loadStudent() {
  const id = workbench.selectedStudentId
  if (!id) { student.value = undefined; return }
  loading.value = true
  student.value = await studentService.getById(id)
  if (student.value) { fillEditForm(student.value); [consultations.value, censusResults.value] = await Promise.all([studentService.getConsultations(id), studentService.getCensusResults(id)]) }
  loading.value = false
}
async function changeRisk(event: Event) { if (!student.value) return; const next = (event.target as HTMLSelectElement).value as RiskLevel; await studentService.updateRiskLevel(student.value.id, next); student.value.riskLevel = next; workbench.notifyStudentsChanged() }
async function saveProfile() { if (!student.value) return; const updated = await studentService.update(student.value.id, { name: editForm.name.trim(), studentNo: editForm.studentNo.trim(), gender: editForm.gender, grade: editForm.grade.trim(), className: editForm.className.trim(), dormNumber: editForm.dormNumber.trim() || undefined, emergencyContact: { name: editForm.contactName.trim(), relation: editForm.relation.trim(), phone: editForm.phone.trim() }, tags: editForm.tags.split(/[，,]/).map((tag) => tag.trim()).filter(Boolean) }); if (updated) { student.value = updated; fillEditForm(updated); workbench.notifyStudentsChanged() } }
async function deleteStudent() { if (!student.value || !window.confirm(`确认删除 ${student.value.name} 的本地档案吗？此操作不可撤销。`)) return; await studentService.remove(student.value.id); student.value = undefined; workbench.selectedStudentId = null; workbench.notifyStudentsChanged() }

watch(() => workbench.selectedStudentId, loadStudent)
onMounted(loadStudent)
</script>

<template>
  <div v-if="loading" class="flex h-full items-center justify-center text-sm text-stone-400">正在读取学生综合心理档案…</div>
  <section v-else-if="!hasStudent" class="flex h-full flex-col items-center justify-center p-8 text-center"><span class="flex size-14 items-center justify-center rounded-2xl bg-teal-50 text-teal-700"><UserRound :size="24" /></span><h1 class="mt-4 text-lg font-semibold text-stone-800">学生综合心理档案</h1><p class="mt-2 max-w-sm text-sm leading-6 text-stone-500">请从中间列表选择学生，查看心理服务与成长履历。</p></section>
  <section v-else class="flex h-full min-h-0 flex-1 flex-col overflow-hidden bg-white">
    <header class="shrink-0 border-b border-stone-200 p-6"><div class="flex flex-wrap items-start justify-between gap-4"><div class="flex items-center gap-3"><span class="flex size-12 items-center justify-center rounded-2xl bg-teal-100 text-xl font-bold text-teal-800">{{ student!.name.slice(0, 1) }}</span><div><div class="flex items-center gap-2"><h1 class="text-xl font-semibold text-stone-800">{{ student!.name }}</h1><span class="text-sm text-stone-400">{{ student!.gender === 'male' ? '♂ 男' : student!.gender === 'female' ? '♀ 女' : '○ 其他' }}</span></div><p class="mt-1 text-sm text-stone-500">{{ student!.studentNo }} · {{ student!.grade }}{{ student!.className }}<span v-if="student!.dormNumber"> · {{ student!.dormNumber }}</span></p></div></div><label class="flex items-center gap-2 rounded-xl px-3 py-2 text-sm font-semibold" :class="riskClass[student!.riskLevel]"><AlertTriangle :size="16" />危机预警等级<select :value="student!.riskLevel" class="bg-transparent text-sm font-semibold outline-none" @change="changeRisk"><option value="normal">正常</option><option value="attention">关注</option><option value="warning">重点关注</option><option value="crisis">危机预警</option></select></label></div><div class="mt-4 flex flex-wrap gap-2"><span v-for="tag in student!.tags" :key="tag" class="rounded-full bg-stone-100 px-2.5 py-1 text-xs font-medium text-stone-600">{{ tag }}</span><span v-if="student!.tags.length === 0" class="text-xs text-stone-400">暂无快捷标签</span></div><p class="mt-4 text-sm text-stone-600">紧急联系人：{{ student!.emergencyContact.name }}（{{ student!.emergencyContact.relation }}） · {{ student!.emergencyContact.phone }}</p></header>
    <nav class="flex shrink-0 overflow-x-auto border-b border-stone-200 px-3 sm:px-5" aria-label="学生档案页签"><button v-for="tab in tabs" :key="tab.id" class="inline-flex shrink-0 items-center gap-1.5 border-b-2 px-3 py-3 text-sm font-medium" :class="activeTab === tab.id ? 'border-teal-700 text-teal-800' : 'border-transparent text-stone-500 hover:text-stone-800'" type="button" @click="activeTab = tab.id"><component :is="tab.icon" :size="15" />{{ tab.label }}</button></nav>
    <div class="min-h-0 flex-1 overflow-y-auto p-6"><StudentTimeline v-if="activeTab === 'timeline'" :student-id="student!.id" :refresh-key="workbench.studentVersion" />
      <div v-else-if="activeTab === 'consultations'" class="space-y-3"><p v-if="consultations.length === 0" class="py-10 text-center text-sm text-stone-400">暂无个体咨询记录。</p><article v-for="record in consultations" v-else :key="record.id" class="rounded-xl border border-stone-200 p-4"><div class="flex flex-wrap items-center justify-between gap-2"><span class="text-sm font-semibold text-stone-800">{{ record.visitType === 'active' ? '主动来访' : record.visitType === 'referral' ? '转介咨询' : '普查约访' }}</span><time class="text-xs text-stone-400">{{ record.date }} · {{ record.durationMinutes }} 分钟</time></div><p class="mt-2 text-sm leading-6 text-stone-600"><span class="font-medium text-stone-700">评估：</span>{{ record.soap.assessment }}</p><p class="mt-1 text-xs text-stone-400">{{ record.problemCategories.join(' · ') }}</p></article></div>
      <div v-else-if="activeTab === 'census'" class="space-y-3"><p v-if="censusResults.length === 0" class="py-10 text-center text-sm text-stone-400">暂无心理普查数据。</p><article v-for="result in censusResults" v-else :key="`${result.batchId}-${result.studentId}`" class="rounded-xl border border-stone-200 p-4"><div class="flex flex-wrap items-start justify-between gap-2"><div><h2 class="text-sm font-semibold text-stone-800">{{ result.batchTitle }}</h2><p class="mt-1 text-xs text-stone-400">{{ result.date }} · {{ result.scaleName }}</p></div><span class="rounded-full px-2 py-0.5 text-xs font-semibold" :class="result.isFlagged ? 'bg-amber-50 text-amber-700' : 'bg-emerald-50 text-emerald-700'">{{ result.isFlagged ? '需关注' : '正常范围' }}</span></div><div class="mt-3 flex flex-wrap gap-2"><span v-for="(score, factor) in result.rawScores" :key="factor" class="rounded-lg bg-stone-100 px-2.5 py-1 text-xs text-stone-600">{{ factor }}：{{ score }}</span></div><p v-if="result.flaggedReasons.length" class="mt-3 text-sm text-amber-700">超标项：{{ result.flaggedReasons.join('；') }}</p></article></div>
      <form v-else class="mx-auto max-w-2xl space-y-5" @submit.prevent="saveProfile"><div class="grid gap-4 sm:grid-cols-2"><label class="text-sm font-medium text-stone-700">姓名<input v-model="editForm.name" required class="mt-1.5 w-full rounded-lg border border-stone-200 px-3 py-2" /></label><label class="text-sm font-medium text-stone-700">学号<input v-model="editForm.studentNo" required class="mt-1.5 w-full rounded-lg border border-stone-200 px-3 py-2" /></label><label class="text-sm font-medium text-stone-700">年级<input v-model="editForm.grade" required class="mt-1.5 w-full rounded-lg border border-stone-200 px-3 py-2" /></label><label class="text-sm font-medium text-stone-700">班级<input v-model="editForm.className" required class="mt-1.5 w-full rounded-lg border border-stone-200 px-3 py-2" /></label><label class="text-sm font-medium text-stone-700">性别<select v-model="editForm.gender" class="mt-1.5 w-full rounded-lg border border-stone-200 px-3 py-2"><option value="female">女</option><option value="male">男</option><option value="other">其他</option></select></label><label class="text-sm font-medium text-stone-700">宿舍号<input v-model="editForm.dormNumber" class="mt-1.5 w-full rounded-lg border border-stone-200 px-3 py-2" /></label><label class="text-sm font-medium text-stone-700">紧急联系人<input v-model="editForm.contactName" class="mt-1.5 w-full rounded-lg border border-stone-200 px-3 py-2" /></label><label class="text-sm font-medium text-stone-700">关系<input v-model="editForm.relation" class="mt-1.5 w-full rounded-lg border border-stone-200 px-3 py-2" /></label><label class="text-sm font-medium text-stone-700">联系电话<input v-model="editForm.phone" class="mt-1.5 w-full rounded-lg border border-stone-200 px-3 py-2" /></label><label class="text-sm font-medium text-stone-700">快捷标签（逗号分隔）<input v-model="editForm.tags" class="mt-1.5 w-full rounded-lg border border-stone-200 px-3 py-2" /></label></div><div class="flex flex-wrap justify-between gap-3 border-t border-stone-100 pt-5"><button type="button" class="inline-flex items-center gap-1.5 rounded-lg px-3 py-2 text-sm font-medium text-rose-600 hover:bg-rose-50" @click="deleteStudent"><Trash2 :size="16" />删除本地档案</button><button class="inline-flex items-center gap-1.5 rounded-lg bg-teal-700 px-4 py-2 text-sm font-semibold text-white hover:bg-teal-800"><Save :size="16" />保存修改</button></div></form>
    </div>
  </section>
</template>
